# **DIANA MARCELA VELASCO**

# **SANTIAGO ALEXIS TOBAR**

# **JUAN CARLOS MOLINA LOZANO**

In [1]:
import pandas as pd
import numpy as np

# Cargar el dataset
df = pd.read_csv('/content/car_prices.csv', on_bad_lines='skip')

# Mostrar información general del dataset
print("--- Información General ---")
display(df.info())

# Mostrar las primeras filas
print("\n--- Primeras 5 filas ---")
display(df.head())

--- Información General ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

None

--- Primeras 5 filas ---

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [2]:
# Verificar valores nulos y duplicados
print("--- Valores Nulos por Columna ---")
display(df.isnull().sum())

print("\n--- Cantidad de Filas Duplicadas ---")
print(df.duplicated().sum())

--- Valores Nulos por Columna ---

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

--- Cantidad de Filas Duplicadas ---
0

In [3]:
# 1. Investigar valores no numéricos en 'mmr'
print("--- Muestra de valores no numéricos en mmr ---")
non_numeric_mmr = df[pd.to_numeric(df['mmr'], errors='coerce').isna()]['mmr'].unique()
print(non_numeric_mmr[:10])

# 2. Investigar inconsistencias en 'state'
print("\n--- Valores únicos en 'state' (primeros 20) ---")
print(df['state'].unique()[:20])

# 3. Investigar formato de 'saledate'
print("\n--- Muestra de formatos en 'saledate' ---")
print(df['saledate'].dropna().head())

--- Muestra de valores no numéricos en mmr ---
[nan]

--- Valores únicos en 'state' (primeros 20) ---
['ca' 'tx' 'pa' 'mn' 'az' 'wi' 'tn' 'md' 'fl' 'ne' 'nj' 'nv' 'oh' 'mi'
 'ga' 'va' 'sc' 'nc' 'in' 'il']

--- Muestra de formatos en 'saledate' ---
0    Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1    Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3    Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4    Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
Name: saledate, dtype: object

In [4]:
# 1. Investigar valores no numéricos en 'mmr'
print("--- Muestra de valores no numéricos en mmr ---")
non_numeric_mmr = df[pd.to_numeric(df['mmr'], errors='coerce').isna()]['mmr'].unique()
print(non_numeric_mmr[:10])

# 2. Investigar inconsistencias en 'state'
print("\n--- Valores únicos en 'state' (primeros 20) ---")
print(df['state'].unique()[:20])

# 3. Investigar formato de 'saledate'
print("\n--- Muestra de formatos en 'saledate' ---")
print(df['saledate'].dropna().head())

--- Muestra de valores no numéricos en mmr ---
[nan]

--- Valores únicos en 'state' (primeros 20) ---
['ca' 'tx' 'pa' 'mn' 'az' 'wi' 'tn' 'md' 'fl' 'ne' 'nj' 'nv' 'oh' 'mi'
 'ga' 'va' 'sc' 'nc' 'in' 'il']

--- Muestra de formatos en 'saledate' ---
0    Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1    Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2    Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3    Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4    Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
Name: saledate, dtype: object

In [6]:
import os
import pandas as pd

# 1. Crear una copia de los datos originales
df_simple = df.copy()

# 2. Convertir 'mmr' y 'sellingprice' a numérico y eliminar nulos
df_simple['mmr'] = pd.to_numeric(df_simple['mmr'], errors='coerce')
df_simple['sellingprice'] = pd.to_numeric(df_simple['sellingprice'], errors='coerce')
df_simple = df_simple.dropna(subset=['sellingprice', 'mmr'])

# 3. Limpiar estados a mayúsculas y filtrar códigos inconsistentes (que no tengan 2 letras)
df_simple['state'] = df_simple['state'].astype(str).str.upper().str.strip()

df_simple = df_simple[df_simple['state'].str.len() == 2]

# 4. Limpiar fechas (reemplazando la columna 'saledate' por una limpia de formato YYYY-MM-DD)
def parse_saledate_simple(date_str):
    try:
        parts = str(date_str).split()
        if len(parts) >= 4:
            date_part = f"{parts[1]} {parts[2]} {parts[3]}"
            return pd.to_datetime(date_part, format='%b %d %Y').strftime('%Y-%m-%d')
    except:
        return None

df_simple['saledate'] = df_simple['saledate'].apply(parse_saledate_simple)
df_simple = df_simple.dropna(subset=['saledate'])

# 5. Guardar el archivo limpio sin columnas adicionales
simple_output_path = '/content/car_prices_limpio.csv'
df_simple.to_csv(simple_output_path, index=False)

# 6. Validar tamaño final del archivo
tamano_bytes = os.path.getsize(simple_output_path)
tamano_mb = tamano_bytes / (1024 * 1024)

print(f"¡Limpieza sin campos adicionales completada!")
print(f"Filas resultantes: {len(df_simple)}")
print(f"Tamaño del nuevo archivo: {tamano_mb:.2f} MB")


print(f"¡Limpieza completada con éxito! Archivo guardado en: {simple_output_path}")
print(f"Filas originales: {len(df)} | Filas limpias finales: {len(df_simple)}")

¡Limpieza sin campos adicionales completada!
Filas resultantes: 558799
Tamaño del nuevo archivo: 72.22 MB
¡Limpieza completada con éxito! Archivo guardado en: /content/car_prices_limpio.csv
Filas originales: 558837 | Filas limpias finales: 558799

In [7]:
# Vamos a identificar exactamente cuáles fueron los 38 registros eliminados y la razón

# 1. Filas originales
filas_originales = set(df.index)

# 2. Filas que sobrevivieron a la limpieza
filas_limpias = set(df_simple.index)

# 3. Filas eliminadas
filas_eliminadas_indices = filas_originales - filas_limpias
df_eliminados = df.loc[list(filas_eliminadas_indices)].copy()

print(f"Total de registros eliminados: {len(df_eliminados)}\n")

# 4. Clasificar por qué se eliminaron
nulos_precio_o_mmr = df_eliminados[df_eliminados['sellingprice'].isnull() | df_eliminados['mmr'].isnull()]

# Intentar parsear la fecha en los eliminados para ver si falló por fecha
def test_date(val):
    try:
        parts = str(val).split()
        if len(parts) >= 4:
            pd.to_datetime(f"{parts[1]} {parts[2]} {parts[3]}", format='%b %d %Y')
            return False
    except:
        pass
    return True

nulos_fecha = df_eliminados[df_eliminados['saledate'].apply(test_date)]
estado_incorrecto = df_eliminados[df_eliminados['state'].astype(str).str.strip().str.len() != 2]

print(f"- Eliminados por precio o MMR vacío (nulo): {len(nulos_precio_o_mmr)}")
print(f"- Eliminados por fecha con formato corrupto o vacía: {len(nulos_fecha)}")
print(f"- Eliminados por código de estado incorrecto (diferente de 2 letras): {len(estado_incorrecto)}")

# Mostrar una muestra de los registros eliminados para comprobarlos
if len(df_eliminados) > 0:
    print("\nMuestra de las filas eliminadas:")
    display(df_eliminados[['state', 'saledate', 'sellingprice', 'mmr']].head(10))

Total de registros eliminados: 38

- Eliminados por precio o MMR vacío (nulo): 38
- Eliminados por fecha con formato corrupto o vacía: 38
- Eliminados por código de estado incorrecto (diferente de 2 letras): 26

Muestra de las filas eliminadas:

                    state saledate  sellingprice  mmr
499083  3vwd17aj5fm268964     9900       13900.0  NaN
520461  3vwd17ajxfm315938     8500       14100.0  NaN
306447                 il      NaN           NaN  NaN
543129                 il      NaN           NaN  NaN
461597  3vwd17aj9fm219766    13000       13900.0  NaN
427040  3vwd17aj0fm227318    14300       13700.0  NaN
431905                 va      NaN           NaN  NaN
453794  3vwd17aj5fm219943    13600       13600.0  NaN
427043  3vwd17aj6fm218641    14500       13850.0  NaN
421289  3vwd17aj3fm276741    12700       13200.0  NaN

In [8]:
import pandas as pd
import numpy as np

# 1. Cantidad de nulos reales en las columnas de interés
print("--- Valores nulos/vacíos actuales en df_simple ---")
columnas = ['make', 'model', 'trim', 'body', 'odometer', 'color', 'interior', 'seller']
nulos = df_simple[columnas].isnull().sum()
for col, cant in nulos.items():
    pct = (cant / len(df_simple)) * 100
    print(f"{col}: {cant} nulos ({pct:.3f}%)")

# 2. Buscar caracteres inconsistentes como 'â€”' o guiones similares en campos de texto
print("\n--- Detección de caracteres corruptos (ej. 'â€”') o guiones ---")
for col in ['make', 'model', 'trim', 'body', 'color', 'interior']:
    # Buscamos patrones típicos de codificación corrupta o guiones de marcador de posición
    inconsistentes = df_simple[df_simple[col].astype(str).str.contains('â|—|~|-\s*$', na=False, regex=True)]
    cant_inc = len(inconsistentes)
    pct_inc = (cant_inc / len(df_simple)) * 100
    print(f"{col}: {cant_inc} registros con caracteres sospechosos ({pct_inc:.3f}%)")

# 3. Analizar la columna 'seller' para ver la necesidad de unificación
print("\n--- Análisis de la columna 'seller' (Vendedores) ---")
print(f"Cantidad de vendedores únicos antes de unificar: {df_simple['seller'].nunique()}")
print("Muestra de algunos vendedores (Top 10):")
display(df_simple['seller'].value_counts().head(10))

<>:16: SyntaxWarning: invalid escape sequence '\s'
<>:16: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_19947/3903853138.py:16: SyntaxWarning: invalid escape sequence '\s'
  inconsistentes = df_simple[df_simple[col].astype(str).str.contains('â|—|~|-\s*$', na=False, regex=True)]

--- Valores nulos/vacíos actuales en df_simple ---
make: 10301 nulos (1.843%)
model: 10399 nulos (1.861%)
trim: 10651 nulos (1.906%)
body: 13195 nulos (2.361%)
odometer: 94 nulos (0.017%)
color: 749 nulos (0.134%)
interior: 749 nulos (0.134%)
seller: 0 nulos (0.000%)

--- Detección de caracteres corruptos (ej. 'â€”') o guiones ---
make: 0 registros con caracteres sospechosos (0.000%)
model: 0 registros con caracteres sospechosos (0.000%)
trim: 0 registros con caracteres sospechosos (0.000%)
body: 0 registros con caracteres sospechosos (0.000%)
color: 24685 registros con caracteres sospechosos (4.418%)
interior: 17075 registros con caracteres sospechosos (3.056%)

--- Análisis de la columna 'seller' (Vendedores) ---
Cantidad de vendedores únicos antes de unificar: 14260
Muestra de algunos vendedores (Top 10):

seller
nissan-infiniti lt                       19693
ford motor credit company llc            19162
the hertz corporation                    18299
santander consumer                       15285
avis corporation                         12540
nissan infiniti lt                        9962
wells fargo dealer services               8796
tdaf remarketing                          7209
enterprise veh exchange/rental            6853
ge fleet services for itself/servicer     6692
Name: count, dtype: int64

In [9]:
import pandas as pd
import numpy as np

# Trabajamos sobre una copia limpia para no alterar el progreso
df_simple_v2 = df_simple.copy()

# 1. Imputar make, model, trim y body con "No Especificado"
for col in ['make', 'model', 'trim', 'body']:
    df_simple_v2[col] = df_simple_v2[col].fillna("No Especificado")

# 2. Imputar odometer con 0
df_simple_v2['odometer'] = df_simple_v2['odometer'].fillna(0)

# 3. Limpiar color e interior (reemplazar nulos y caracteres sospechosos por "No Especificado")
# Definimos un patrón para capturar guiones o caracteres extraños de codificación corrupta
patron_inconsistente = r'â|—|~|^\s*-\s*$'

for col in ['color', 'interior']:
    # Primero rellenamos nulos con un texto temporal
    df_simple_v2[col] = df_simple_v2[col].fillna("No Especificado")
    # Luego reemplazamos los caracteres sospechosos
    df_simple_v2[col] = df_simple_v2[col].apply(lambda x: "No Especificado" if pd.Series(str(x)).str.contains(patron_inconsistente, regex=True).iloc[0] else x)

# 4. Limpieza recomendada de la columna 'seller'
# Paso 4.1: Convertir a mayúsculas y limpiar espacios en blanco
df_simple_v2['seller'] = df_simple_v2['seller'].astype(str).str.upper().str.strip()

# Paso 4.2: Agrupar vendedores minoristas (menos de 50 ventas en el dataset)
#conteo_vendedores = df_simple_v2['seller'].value_counts()
#vendedores_pequenos = conteo_vendedores[conteo_vendedores < 50].index
#df_simple_v2['seller'] = df_simple_v2['seller'].replace(vendedores_pequenos, "OTROS VENDEDORES")

# 5. Guardar la nueva versión del archivo limpio
cleaned_v2_path = '/content/car_prices_limpio_v2.csv'
df_simple_v2.to_csv(cleaned_v2_path, index=False)

# 6. Validar que no queden nulos ni caracteres corruptos
print("--- Verificación de Nulos en el nuevo Dataset ---")
print(df_simple_v2[['make', 'model', 'trim', 'body', 'odometer', 'color', 'interior', 'seller']].isnull().sum())

print("\n--- Verificación de caracteres corruptos en color/interior ---")
print("Casos en color:", df_simple_v2[df_simple_v2['color'].str.contains(patron_inconsistente, na=False, regex=True)].shape[0])
print("Casos en interior:", df_simple_v2[df_simple_v2['interior'].str.contains(patron_inconsistente, na=False, regex=True)].shape[0])

print(f"\n--- Análisis de Seller ---")
print(f"Vendedores únicos resultantes: {df_simple_v2['seller'].nunique()}")
print("Muestra de vendedores unificados:")
display(df_simple_v2['seller'].value_counts().head(10))

print(f"\n¡Nuevo dataset guardado con éxito en: {cleaned_v2_path}!")

--- Verificación de Nulos en el nuevo Dataset ---
make        0
model       0
trim        0
body        0
odometer    0
color       0
interior    0
seller      0
dtype: int64

--- Verificación de caracteres corruptos en color/interior ---
Casos en color: 0
Casos en interior: 0

--- Análisis de Seller ---
Vendedores únicos resultantes: 14260
Muestra de vendedores unificados:

seller
NISSAN-INFINITI LT                       19693
FORD MOTOR CREDIT COMPANY LLC            19162
THE HERTZ CORPORATION                    18299
SANTANDER CONSUMER                       15285
AVIS CORPORATION                         12540
NISSAN INFINITI LT                        9962
WELLS FARGO DEALER SERVICES               8796
TDAF REMARKETING                          7209
ENTERPRISE VEH EXCHANGE/RENTAL            6853
GE FLEET SERVICES FOR ITSELF/SERVICER     6692
Name: count, dtype: int64

¡Nuevo dataset guardado con éxito en: /content/car_prices_limpio_v2.csv!

### **Conclusión del Proceso de Limpieza, Saneamiento y Preparación de Datos (Versión Final)**

Para asegurar la máxima calidad de los datos y un rendimiento óptimo en la integración con **Google Looker Studio**, se implementó un pipeline de preparación estructurado en dos fases consecutivas:

---

#### **Fase 1: Depuración de Registros Críticos e Inconsistencias Estructurales**
1. **Lectura e Inspección Inicial:** Se importó el conjunto de datos original con **558,837 registros**, identificando columnas con datos nulos y discrepancias de formato.
2. **Saneamiento Financiero (`sellingprice` y `mmr`):** Se forzó la conversión a tipo numérico de los precios de venta y la tasación MMR, lo que permitió identificar y remover únicamente **38 registros** que carecían de estas métricas esenciales para la construcción de KPIs económicos.
3. **Normalización Geográfica (`state`):** Se transformaron los códigos de estado a mayúsculas (`str.upper()`) y se descartaron los registros cuyas abreviaturas no correspondían al estándar oficial de dos caracteres.
4. **Conversión Temporal (`saledate`):** Se transformaron las complejas cadenas de fecha originales (con husos horarios extensos) a un formato de fecha simple estándar (`YYYY-MM-DD`), esencial para análisis evolutivos en series de tiempo.

---

#### **Fase 2: Tratamiento de Vacíos, Codificación Corrupta y Homogeneidad Categórica**
Para evitar la pérdida masiva de información útil que hubiese provocado una eliminación en cadena de registros, se aplicaron tratamientos de imputación y corrección de codificación sobre las variables secundarias:

1. **Imputación Estándar (`make`, `model`, `trim`, `body`):** Se completaron las celdas vacías utilizando la etiqueta **`"No Especificado"`**, preservando el valor comercial de las filas.
2. **Ajuste de Atributo de Uso (`odometer`):** Los registros faltantes en el odómetro se completaron asignándoles un valor de **`0`**, asegurando la integridad del campo numérico.
3. **Neutralización de Errores de Codificación (`color` e `interior`):** Se identificaron y reemplazaron tanto los nulos reales como más de **41,000 celdas** que contenían caracteres de codificación rotos (tales como `â€”`, `—` o `~`), estandarizándolos bajo el término **`"No Especificado"`**.
4. **Normalización de Vendedores (`seller`):** Se homogeneizaron los nombres de las agencias y vendedores llevándolos a un formato uniforme en mayúsculas y libre de espacios en blanco redundantes, conservando el nivel de detalle individual de cada actor comercial en el dataset.

---

**Resultado Final:** El archivo depurado **`car_prices_limpio_v2.csv`** consta de **558,799 registros**, libre de nulos en variables clave, corregido en sus problemas de formato de texto/fecha, y listo para ser explotado en la creación de tableros de control de alta fidelidad.